version: 2

workflows:
  version: 2
  build_api:
    jobs:
      - build_api

jobs:
  build_api:
    docker:
      - image: circleci/golang:1.12 #

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/artifacts # path to where test results will be saved

    steps: # steps that comprise the `build` job
      # check out source code to working directory
      - checkout

      # create the test results directory
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p $TEST_RESULTS

      # restores saved cache if no changes are detected since last run
      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go get -v -t -d ./apiservice/...

      - run: go get -v github.com/mattn/goveralls

      - run:
          name: Run unit tests
          # Store the results of our tests in the /tmp/artifacts directory
          command: |
            go test ./apiservice/... -coverprofile=api_coverage.out
            go tool cover -html=api_coverage.out -o api_coverage.html
            mv api_coverage.out /tmp/artifacts
            mv api_coverage.html /tmp/artifacts

      # - run: make # pull and build dependencies for the project

      # Store cache in the /go/pkg directory
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      - store_artifacts:
          path: /tmp/artifacts
          destination: raw-test-output

      # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      - store_test_results:
          path: /tmp/artifacts

      # Upload test coverage results to Coveralls
      - run:
          name: Upload Coverage Results
          command: |
            goveralls -coverprofile=/tmp/artifacts/coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN
