// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// RoutesHandler is an autogenerated mock type for the RoutesHandler type
type RoutesHandler struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: w, r
func (_m *RoutesHandler) CreatePayment(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DeletePayment provides a mock function with given fields: w, r
func (_m *RoutesHandler) DeletePayment(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DumpPayment provides a mock function with given fields: w, r
func (_m *RoutesHandler) DumpPayment(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// FetchPayment provides a mock function with given fields: w, r
func (_m *RoutesHandler) FetchPayment(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ListPayments provides a mock function with given fields: w, r
func (_m *RoutesHandler) ListPayments(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ListVersions provides a mock function with given fields: w, r
func (_m *RoutesHandler) ListVersions(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdatePayment provides a mock function with given fields: w, r
func (_m *RoutesHandler) UpdatePayment(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
